import { Inter } from '@next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Login from '../../components/container/pages/Login'
import styles from '../../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Login></Login>
    </>
  )
}
