import { Inter } from '@next/font/google'
import Head from 'next/head'
import Room from '../../components/templates/Room'

const inter = Inter({ subsets: ['latin'] })

export default function RoomPage() {
  return (
    <>
      <Head>
        <title>Room</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Room />
    </>
  )
}
